# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: PyPy 3.7, python: 'pypy-3.7', os: ubuntu}
          - {name: Python 3.7, python: '3.7', os: ubuntu}
          - {name: Python 3.8, python: '3.8', os: ubuntu}
          - {name: Python 3.9, python: '3.9', os: ubuntu}
          - {name: Python 3.10, python: '3.10', os: ubuntu}
          - {name: Python 3.11-dev, python: '3.11-dev', os: ubuntu}
          - {name: Windows py37, python: '3.7', os: windows}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry tox tox-poetry codecov
    - name: Tox
      run: |
        python3 -m tox
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
